// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: api/status.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequestUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrUrl             string `protobuf:"bytes,1,opt,name=strUrl,proto3" json:"strUrl,omitempty"`
	CountPointCheckUrl int32  `protobuf:"varint,2,opt,name=countPointCheckUrl,proto3" json:"countPointCheckUrl,omitempty"`
}

func (x *AddRequestUrl) Reset() {
	*x = AddRequestUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRequestUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequestUrl) ProtoMessage() {}

func (x *AddRequestUrl) ProtoReflect() protoreflect.Message {
	mi := &file_api_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequestUrl.ProtoReflect.Descriptor instead.
func (*AddRequestUrl) Descriptor() ([]byte, []int) {
	return file_api_status_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequestUrl) GetStrUrl() string {
	if x != nil {
		return x.StrUrl
	}
	return ""
}

func (x *AddRequestUrl) GetCountPointCheckUrl() int32 {
	if x != nil {
		return x.CountPointCheckUrl
	}
	return 0
}

type AddResponseUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddResponseUrl) Reset() {
	*x = AddResponseUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResponseUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponseUrl) ProtoMessage() {}

func (x *AddResponseUrl) ProtoReflect() protoreflect.Message {
	mi := &file_api_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponseUrl.ProtoReflect.Descriptor instead.
func (*AddResponseUrl) Descriptor() ([]byte, []int) {
	return file_api_status_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponseUrl) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RequestInfoByCheckUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrUrl string `protobuf:"bytes,1,opt,name=strUrl,proto3" json:"strUrl,omitempty"`
}

func (x *RequestInfoByCheckUrl) Reset() {
	*x = RequestInfoByCheckUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInfoByCheckUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfoByCheckUrl) ProtoMessage() {}

func (x *RequestInfoByCheckUrl) ProtoReflect() protoreflect.Message {
	mi := &file_api_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfoByCheckUrl.ProtoReflect.Descriptor instead.
func (*RequestInfoByCheckUrl) Descriptor() ([]byte, []int) {
	return file_api_status_proto_rawDescGZIP(), []int{2}
}

func (x *RequestInfoByCheckUrl) GetStrUrl() string {
	if x != nil {
		return x.StrUrl
	}
	return ""
}

type ResponseInfoByCheckUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeCheckUrl string `protobuf:"bytes,1,opt,name=timeCheckUrl,proto3" json:"timeCheckUrl,omitempty"`
	StatusUrl    string `protobuf:"bytes,2,opt,name=statusUrl,proto3" json:"statusUrl,omitempty"`
}

func (x *ResponseInfoByCheckUrl) Reset() {
	*x = ResponseInfoByCheckUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_status_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseInfoByCheckUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInfoByCheckUrl) ProtoMessage() {}

func (x *ResponseInfoByCheckUrl) ProtoReflect() protoreflect.Message {
	mi := &file_api_status_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInfoByCheckUrl.ProtoReflect.Descriptor instead.
func (*ResponseInfoByCheckUrl) Descriptor() ([]byte, []int) {
	return file_api_status_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseInfoByCheckUrl) GetTimeCheckUrl() string {
	if x != nil {
		return x.TimeCheckUrl
	}
	return ""
}

func (x *ResponseInfoByCheckUrl) GetStatusUrl() string {
	if x != nil {
		return x.StatusUrl
	}
	return ""
}

type RequestUrlDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrUrl string `protobuf:"bytes,1,opt,name=strUrl,proto3" json:"strUrl,omitempty"`
}

func (x *RequestUrlDelete) Reset() {
	*x = RequestUrlDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_status_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUrlDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUrlDelete) ProtoMessage() {}

func (x *RequestUrlDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_status_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUrlDelete.ProtoReflect.Descriptor instead.
func (*RequestUrlDelete) Descriptor() ([]byte, []int) {
	return file_api_status_proto_rawDescGZIP(), []int{4}
}

func (x *RequestUrlDelete) GetStrUrl() string {
	if x != nil {
		return x.StrUrl
	}
	return ""
}

type ResponseUrlDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrUrl string `protobuf:"bytes,1,opt,name=strUrl,proto3" json:"strUrl,omitempty"`
}

func (x *ResponseUrlDelete) Reset() {
	*x = ResponseUrlDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_status_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUrlDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUrlDelete) ProtoMessage() {}

func (x *ResponseUrlDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_status_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUrlDelete.ProtoReflect.Descriptor instead.
func (*ResponseUrlDelete) Descriptor() ([]byte, []int) {
	return file_api_status_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseUrlDelete) GetStrUrl() string {
	if x != nil {
		return x.StrUrl
	}
	return ""
}

var File_api_status_proto protoreflect.FileDescriptor

var file_api_status_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x57, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x55, 0x72, 0x6c,
	0x12, 0x2e, 0x0a, 0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c,
	0x22, 0x28, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2f, 0x0a, 0x15, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x5a, 0x0a, 0x16, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x55, 0x72, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72,
	0x55, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55,
	0x72, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x55, 0x72, 0x6c,
	0x32, 0xc5, 0x01, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x33, 0x0a, 0x06, 0x41, 0x64,
	0x64, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x72, 0x6c, 0x12,
	0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x1a, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x16,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x72, 0x6c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_status_proto_rawDescOnce sync.Once
	file_api_status_proto_rawDescData = file_api_status_proto_rawDesc
)

func file_api_status_proto_rawDescGZIP() []byte {
	file_api_status_proto_rawDescOnce.Do(func() {
		file_api_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_status_proto_rawDescData)
	})
	return file_api_status_proto_rawDescData
}

var file_api_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_status_proto_goTypes = []interface{}{
	(*AddRequestUrl)(nil),          // 0: api.AddRequestUrl
	(*AddResponseUrl)(nil),         // 1: api.AddResponseUrl
	(*RequestInfoByCheckUrl)(nil),  // 2: api.RequestInfoByCheckUrl
	(*ResponseInfoByCheckUrl)(nil), // 3: api.ResponseInfoByCheckUrl
	(*RequestUrlDelete)(nil),       // 4: api.RequestUrlDelete
	(*ResponseUrlDelete)(nil),      // 5: api.ResponseUrlDelete
}
var file_api_status_proto_depIdxs = []int32{
	0, // 0: api.Check.AddUrl:input_type -> api.AddRequestUrl
	2, // 1: api.Check.GetStatusUrl:input_type -> api.RequestInfoByCheckUrl
	4, // 2: api.Check.DeleteUrl:input_type -> api.RequestUrlDelete
	1, // 3: api.Check.AddUrl:output_type -> api.AddResponseUrl
	3, // 4: api.Check.GetStatusUrl:output_type -> api.ResponseInfoByCheckUrl
	5, // 5: api.Check.DeleteUrl:output_type -> api.ResponseUrlDelete
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_status_proto_init() }
func file_api_status_proto_init() {
	if File_api_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRequestUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResponseUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInfoByCheckUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_status_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseInfoByCheckUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_status_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUrlDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_status_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUrlDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_status_proto_goTypes,
		DependencyIndexes: file_api_status_proto_depIdxs,
		MessageInfos:      file_api_status_proto_msgTypes,
	}.Build()
	File_api_status_proto = out.File
	file_api_status_proto_rawDesc = nil
	file_api_status_proto_goTypes = nil
	file_api_status_proto_depIdxs = nil
}
